$(document).ready(function(){
                    $('.banner').owlCarousel({
                            loop:true,
                            margin:0,
                            nav:false,
                            autoplay:true,
                            smartSpeed:2000,
                            responsive:{
                                0:{
                                    items:1
                                },
                                600:{
                                    items:1
                                },
                                1000:{
                                    items:1
                                }
                            }
                        });
                    $('.fruitlist .owl-carousel').owlCarousel({
                        loop:true,
                        margin:10,
                        nav:true,
                        responsive:{
                            0:{
                                items:1
                            },
                            600:{
                                items:4
                            },
                            1000:{
                                items:4
                            }
                        }
                    });
                     $('.photo2 .owl-carousel').owlCarousel({
                        loop:true,
                        margin:10,
                        nav:false,
                        responsive:{
                            0:{
                                items:1
                            },
                            600:{
                                items:4
                            },
                            1000:{
                                items:4
                            }
                        }
                    });
                      $('.blogphoto .owl-carousel').owlCarousel({
                        loop:false,
                        margin:10,
                        nav:false,
                        responsive:{
                            0:{
                                items:1
                            },
                            600:{
                                items:3
                            },
                            1000:{
                                items:3
                            }
                        }
                    });
                       $('.testi .owl-carousel').owlCarousel({
                        loop:true,
                        margin:10,
                        nav:false,
                        responsive:{
                            0:{
                                items:1
                            },
                            600:{
                                items:1
                            },
                            1000:{
                                items:1
                            }
                        }
                    });
});

